sonar.projectKey=vikasvr1997_vertex-agentic-chatbot
sonar.organization=vikasvr1997

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11,3.12

sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.egg-info/**
sonar.test.exclusions=tests/**

sonar.sourceEncoding=UTF-8
