"""Resolves a user-provided table/column name that may not literally match
the schema (different naming convention, synonym, typo) to the real
BigQuery table/column. Looks up the alias table generated by
alias_generator.py first (exact match, then fuzzy match), and falls back to
an on-the-fly Vertex AI call against the full catalog if nothing matches --
so lookups keep working even for terms nobody anticipated when aliases were
generated.

Usage: python3 alias_resolver.py --project-id my-project --term "chauffeur"
"""

import argparse
import difflib
import json

from google.cloud import bigquery

try:
    import vertexai
    from vertexai.generative_models import GenerativeModel

    _VERTEX_AVAILABLE = True
except ImportError:
    _VERTEX_AVAILABLE = False


def _normalize(s):
    return s.lower().strip().replace("-", " ").replace("_", " ")


def _dedupe(rows):
    seen, out = set(), []
    for r in rows:
        key = (r["table_name"], r["column_name"])
        if key not in seen:
            seen.add(key)
            out.append(dict(r))
    return out


def resolve(project_id, user_term, vertex_location="us-central1"):
    client = bigquery.Client(project=project_id)
    rows = list(
        client.query(f"""
        SELECT dataset_id, table_name, column_name, alias
        FROM `{project_id}.global_governance_ds.node_aliases`
    """).result()
    )

    target = _normalize(user_term)
    exact = [
        r
        for r in rows
        if _normalize(r["alias"]) == target
        or _normalize(r["table_name"]) == target
        or (r["column_name"] and _normalize(r["column_name"]) == target)
    ]
    if exact:
        return _dedupe(exact)

    candidates = {_normalize(r["alias"]): r for r in rows}
    close = difflib.get_close_matches(target, candidates.keys(), n=3, cutoff=0.72)
    if close:
        return _dedupe([candidates[c] for c in close])

    if _VERTEX_AVAILABLE:
        try:
            vertexai.init(project=project_id, location=vertex_location)
            model = GenerativeModel("gemini-1.5-flash")
            catalog = [{"table": r["table_name"], "column": r["column_name"]} for r in rows][:200]
            prompt = (
                f"A user referred to '{user_term}'. Given this catalog of tables "
                f"and columns: {json.dumps(catalog)}, return ONLY JSON: "
                '{"table_name": "...", "column_name": "..." or null} '
                "for the single best match, or {} if nothing plausibly matches."
            )
            response = model.generate_content(prompt)
            text = response.text.strip().strip("`")
            if text.startswith("json"):
                text = text[4:].strip()
            parsed = json.loads(text)
            if parsed.get("table_name"):
                return [
                    {"table_name": parsed["table_name"], "column_name": parsed.get("column_name")}
                ]
        except Exception:
            pass

    return []


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-id", required=True)
    parser.add_argument("--term", required=True)
    args = parser.parse_args()
    print(json.dumps(resolve(args.project_id, args.term), indent=2))
