"""Pydantic request/response models for the internal chat API."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=8000)
    session_id: str | None = Field(default=None, description="Omit to start a new session.")
    settings: dict[str, Any] | None = Field(
        default=None,
        description="Optional per-request overrides, e.g. {'model': 'gemini-2.0-flash-001'}. "
        "A model override only takes effect when starting a brand-new session.",
    )


class ChatResponse(BaseModel):
    session_id: str
    reply: str
    turn_count: int
    generated_query: str | None = Field(
        default=None,
        description="SQL generated by the BigQuery agent, if this turn was routed there.",
    )
    table: list[dict[str, Any]] | None = Field(
        default=None, description="Rows returned by the generated query, if any."
    )
    chart: dict[str, Any] | None = Field(
        default=None, description="Chart spec: {type, x, y, title, x_label, y_label}."
    )


class HealthResponse(BaseModel):
    status: str
    environment: str


class StatusResponse(BaseModel):
    """Non-secret configuration surfaced to the frontends' sidebar/settings UI."""

    google_cloud_project: str
    google_cloud_location: str
    vertex_model_name: str
    backend_mode: str
    bigquery_dataset: str | None
